#!/bin/bash

declare -a arr=('The 1'
'22'
'Afterglow'
'All Too Well'
'All You Had to Do Was Stay'
'The Archer'
'August'
'Babe'
'Back to December'
'Bad Blood'
'Beautiful Eyes'
'Beautiful Ghosts'
'Begin Again'
'The Best Day'
'Better than Revenge'
'Betty'
'Blank Space'
'Both of Us'
'Breathe'
'Breathless'
"Call It What You Want"
"Cardigan"
"Champagne Problems"
"Change"
"Christmas Tree Farm"
"Clean"
"Closure"
"Cold as You"
"Come Back... Be Here"
"Come in with the Rain"
"Coney Island"
"Cornelia Street"
"Cowboy Like Me"
"Crazier"
"Cruel Summer"
"Dancing with Our Hands Tied"
"Daylight"
"Death by a Thousand Cuts"
"Dear John"
"Delicate"
"Don't Blame Me"
"Dorothea"
"Dress"
"Enchanted"
"End Game"
"Epiphany"
"Evermore"
"Everything Has Changed"
"Exile"
"Eyes Open"
"False God"
"Fearless"
"Fifteen"
"Forever & Always"
"Getaway Car"
"Girl at Home"
"Gold Rush"
"Gorgeous"
"Happiness"
"Haunted"
"Hey Stephen"
"Highway Don't Care"
"Hoax"
"Holy Ground"
"How You Get the Girl"
"I Almost Do"
"I Did Something Bad"
"I Don't Wanna Live Forever"
"I Forgot That You Existed"
"I Heart"
"I Knew You Were Trouble"
"I Know Places"
"I Think He Knows"
"I Wish You Would"
"If This Was a Movie"
"Illicit Affairs"
"Innocent"
"Invisible"
"Invisible String"
"It's Nice to Have a Friend"
"It's Time to Go"
"I'm Only Me When I'm with You"
"Ivy"
"Jump Then Fall"
"King of My Heart"
"The Lakes"
"The Last Great American Dynasty"
"Last Kiss"
"The Last Time"
"Long Live"
"Long Story Short"
"London Boy"
"Look What You Made Me Do"
"Love Story"
"Lover"
"Lover (Remix)"
"The Lucky One"
"Mad Woman"
"The Man"
"Marjorie"
"Me!"
"Mean"
"Mine"
"Mirrorball"
"Miss Americana & the Heartbreak Prince"
"The Moment I Knew"
"My Tears Ricochet"
"Never Grow Up"
"New Romantics"
"New Year's Day"
"No Body, No Crime"
"Only the Young"
"The Other Side of the Door"
"Our Song"
"Ours"
"Out of the Woods"
"The Outside"
"Paper Rings"
"Peace"
"A Perfectly Good Heart"
"Picture to Burn"
"A Place in This World"
"...Ready for It?"
"Red"
"Right Where You Left Me"
"Ronan"
"Sad Beautiful Tragic"
"Safe & Sound"
"Seven"
"Shake It Off"
"Should've Said No"
"So It Goes..."
"Soon You'll Get Better"
"Sparks Fly"
"Speak Now"
"Starlight"
"State of Grace"
"Stay Beautiful"
"Stay Stay Stay"
"The Story of Us"
"Style"
"Superman"
"Superstar"
"Sweeter than Fiction"
"Teardrops on My Guitar"
"Tell Me Why"
"This Is Me Trying"
"This Is Why We Can't Have Nice Things"
"This Love"
"Tied Together with a Smile"
"Tim McGraw"
"'Tis the Damn Season"
"Today Was a Fairytale"
"Tolerate It"
"Treacherous"
"Two Is Better Than One"
"Untouchable"
"The Way I Loved You"
"We Are Never Ever Getting Back Together"
"Welcome to New York"
"White Horse"
"Wildest Dreams"
"Willow"
"Wonderland"
"You Are in Love"
"You Belong with Me"
"You Need to Calm Down"
"You're Not Sorry"
)

arraylength=${#array[@]}

figlet -c ${arr[RANDOM%${#arr[@]}]}
